"""empty message

Revision ID: 00006
Revises: 00005
Create Date: 2025-08-15 15:14:44.526087

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00006'
down_revision: Union[str, None] = '00005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('guest_id', sa.UUID(), nullable=True))
    op.alter_column('booking', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'booking', 'guest', ['guest_id'], ['id'])
    op.drop_constraint('guest_booking_id_key', 'guest', type_='unique')
    op.drop_constraint('guest_booking_id_fkey', 'guest', type_='foreignkey')
    op.drop_column('guest', 'booking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('guest_booking_id_fkey', 'guest', 'booking', ['booking_id'], ['id'])
    op.create_unique_constraint('guest_booking_id_key', 'guest', ['booking_id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.alter_column('booking', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('booking', 'guest_id')
    # ### end Alembic commands ###
