"""empty message

Revision ID: 00009
Revises: 00008
Create Date: 2025-09-18 15:51:56.355280

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00009'
down_revision: Union[str, None] = '00008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('stripe_refund_id', sa.String(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refund_reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_refund_id')
    )
    op.create_index(op.f('ix_refund_created_at'), 'refund', ['created_at'], unique=False)
    op.create_index(op.f('ix_refund_id'), 'refund', ['id'], unique=False)
    op.add_column('booking', sa.Column('intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'intent_id')
    op.drop_index(op.f('ix_refund_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_created_at'), table_name='refund')
    op.drop_table('refund')
    # ### end Alembic commands ###
