"""empty message

Revision ID: 00003
Revises: 00002
Create Date: 2025-06-07 16:33:18.832909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00003'
down_revision: Union[str, None] = '00002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('room', sa.Column('description', sa.String(), nullable=False))
    op.add_column('room', sa.Column('total_space', sa.Float(), nullable=False))
    op.add_column('room', sa.Column('has_sauna', sa.Boolean(), nullable=False))
    op.add_column('room', sa.Column('has_jacuzzi', sa.Boolean(), nullable=False))
    op.drop_column('room', 'sauna')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('sauna', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('room', 'has_jacuzzi')
    op.drop_column('room', 'has_sauna')
    op.drop_column('room', 'total_space')
    op.drop_column('room', 'description')
    op.drop_column('room', 'capacity')
    # ### end Alembic commands ###
