"""adding image in binary

Revision ID: 00002
Revises: 00001
Create Date: 2025-04-12 14:04:50.673219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00002'
down_revision: Union[str, None] = '00001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'payment_status')
    op.add_column('property', sa.Column('image', sa.LargeBinary(length=16777216), nullable=False))
    op.drop_column('property', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('property', 'image')
    op.add_column('booking', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
