"""empty message

Revision ID: 00004
Revises: 00003
Create Date: 2025-06-22 22:40:48.714789

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00004'
down_revision: Union[str, None] = '00003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('whether_send_confirmation', sa.Boolean(), nullable=False),
    sa.Column('is_booking_for_me', sa.Boolean(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_guest_created_at'), 'guest', ['created_at'], unique=False)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=False)
    op.add_column('booking', sa.Column('special_requests', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'special_requests')
    op.drop_index(op.f('ix_guest_id'), table_name='guest')
    op.drop_index(op.f('ix_guest_created_at'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
