"""Adding price to booking

Revision ID: 00004
Revises: 00003
Create Date: 2025-04-15 10:23:57.733693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00004'
down_revision: Union[str, None] = '00003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('price', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('booking', 'price')
    # ### end Alembic commands ###
