"""empty message

Revision ID: 00008
Revises: 00007
Create Date: 2025-09-09 16:11:13.890116

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00008'
down_revision: Union[str, None] = '00007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_user_id_fkey', 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    op.add_column('user', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'image_id')
    op.add_column('image', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('image_user_id_fkey', 'image', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
