"""Booking id in review

Revision ID: 00017
Revises: 00016
Create Date: 2026-01-20 20:35:06.886486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00017'
down_revision: Union[str, None] = '00016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_review_booking', 'review', ['booking_id'])
    op.create_unique_constraint(None, 'review', ['booking_id'])
    op.create_foreign_key(None, 'review', 'booking', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='unique')
    op.drop_constraint('uq_review_booking', 'review', type_='unique')
    op.drop_column('review', 'booking_id')
    # ### end Alembic commands ###
