"""Adding verification token table

Revision ID: 00018
Revises: 00017
Create Date: 2026-01-22 15:00:31.303209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00018'
down_revision: Union[str, None] = '00017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_token',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_token_created_at'), 'verification_token', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_token_id'), 'verification_token', ['id'], unique=False)
    op.create_index(op.f('ix_verification_token_token'), 'verification_token', ['token'], unique=True)
    op.create_index(op.f('ix_verification_token_user_id'), 'verification_token', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.drop_index(op.f('ix_verification_token_user_id'), table_name='verification_token')
    op.drop_index(op.f('ix_verification_token_token'), table_name='verification_token')
    op.drop_index(op.f('ix_verification_token_id'), table_name='verification_token')
    op.drop_index(op.f('ix_verification_token_created_at'), table_name='verification_token')
    op.drop_table('verification_token')
    # ### end Alembic commands ###
