"""Deleting verification token logic

Revision ID: 00019
Revises: 00018
Create Date: 2026-01-23 10:24:43.914504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00019'
down_revision: Union[str, None] = '00018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_token_created_at', table_name='verification_token')
    op.drop_index('ix_verification_token_id', table_name='verification_token')
    op.drop_index('ix_verification_token_token', table_name='verification_token')
    op.drop_index('ix_verification_token_user_id', table_name='verification_token')
    op.drop_table('verification_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('verification_token',
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='verification_token_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='verification_token_pkey')
    )
    op.create_index('ix_verification_token_user_id', 'verification_token', ['user_id'], unique=False)
    op.create_index('ix_verification_token_token', 'verification_token', ['token'], unique=True)
    op.create_index('ix_verification_token_id', 'verification_token', ['id'], unique=False)
    op.create_index('ix_verification_token_created_at', 'verification_token', ['created_at'], unique=False)
    # ### end Alembic commands ###
