"""Rating table

Revision ID: 00012
Revises: 00011
Create Date: 2025-10-07 15:42:41.028344

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00012'
down_revision: Union[str, None] = '00011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('staff_rate', sa.Integer(), nullable=False),
    sa.Column('cleanliness_rate', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('recommended_for_friends', sa.Boolean(), nullable=False),
    sa.Column('stay_again', sa.Boolean(), nullable=False),
    sa.Column('experience_comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cleanliness_rate >= 1 AND cleanliness_rate <= 4', name='check_cleanliness_rate_range'),
    sa.CheckConstraint('staff_rate >= 1 AND staff_rate <= 4', name='check_staff_rate_range'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_created_at'), 'rating', ['created_at'], unique=False)
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.add_column('room', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'average_rating')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_created_at'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
