"""Cascades added

Revision ID: 00013
Revises: 00012
Create Date: 2025-10-27 18:31:27.964796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00013'
down_revision: Union[str, None] = '00012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_room_id_fkey', 'booking', type_='foreignkey')
    op.drop_constraint('booking_guest_id_fkey', 'booking', type_='foreignkey')
    op.drop_constraint('booking_user_id_fkey', 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking', 'guest', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('refresh_token_user_id_fkey', 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('refund', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('refund_booking_id_fkey', 'refund', type_='foreignkey')
    op.create_foreign_key(None, 'refund', 'booking', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refund', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('review_room_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_image_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'image', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_image_id_fkey', 'user', 'image', ['image_id'], ['id'])
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['id'])
    op.create_foreign_key('review_room_id_fkey', 'review', 'room', ['room_id'], ['id'])
    op.drop_constraint(None, 'refund', type_='foreignkey')
    op.drop_constraint(None, 'refund', type_='foreignkey')
    op.create_foreign_key('refund_booking_id_fkey', 'refund', 'booking', ['booking_id'], ['id'])
    op.drop_column('refund', 'user_id')
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.create_foreign_key('refresh_token_user_id_fkey', 'refresh_token', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key('booking_user_id_fkey', 'booking', 'user', ['user_id'], ['id'])
    op.create_foreign_key('booking_guest_id_fkey', 'booking', 'guest', ['guest_id'], ['id'])
    op.create_foreign_key('booking_room_id_fkey', 'booking', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###
