"""empty message

Revision ID: 00011
Revises: 00010
Create Date: 2025-09-25 23:03:42.515046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00011'
down_revision: Union[str, None] = '00010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('user', 'money_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money_balance', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
