"""Adding hash for tokens

Revision ID: 00016
Revises: 00015
Create Date: 2026-01-18 22:32:14.988306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00016'
down_revision: Union[str, None] = '00015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('token_hash', sa.String(length=512), nullable=False))
    op.drop_index('ix_refresh_token_token', table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.drop_column('refresh_token', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.create_index('ix_refresh_token_token', 'refresh_token', ['token'], unique=True)
    op.drop_column('refresh_token', 'token_hash')
    # ### end Alembic commands ###
