"""Deleting guest table

Revision ID: 00020
Revises: 00019
Create Date: 2026-01-23 11:28:24.644336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00020'
down_revision: Union[str, None] = '00019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_guest_id_fkey', 'booking', type_='foreignkey')
    op.drop_column('booking', 'guest_id')
    op.drop_index('ix_guest_created_at', table_name='guest')
    op.drop_index('ix_guest_id', table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('guest_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('booking_guest_id_fkey', 'booking', 'guest', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_table('guest',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('whether_send_confirmation', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_booking_for_me', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='guest_pkey')
    )
    op.create_index('ix_guest_id', 'guest', ['id'], unique=False)
    op.create_index('ix_guest_created_at', 'guest', ['created_at'], unique=False)
    # ### end Alembic commands ###
