"""Delete in image relation

Revision ID: 00021
Revises: 00020
Create Date: 2026-01-24 22:34:01.301009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00021'
down_revision: Union[str, None] = '00020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_image_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_image_id_fkey', 'user', 'image', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
